# Generated by Django 3.1 on 2022-02-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telesettings',
            name='tg_token',
            field=models.CharField(default=1, max_length=200, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
